language: python
python:
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: T0BeO0yhmB0DTBtSC3kmwQS7OXE2g+E5XgqWckMF849/wCIKQbxlhiyH4Nje9PiFZGjQE5RcccKE+n+X4709Irz42PvIe3XvE40Y/FwAnTp3q/gKXJDqnUt2RBQpZ2Mt0Pf8P9rDS8Qk/tYgWD7gMLlkPlLFizqLJhoNwpjsgo3yb+Ga6NmxLX0FRmmDSVO9QhD+Je3UHNsiJ0hjkApL9kltcMxVMIwIeK7+ZkH3FSId7iHaMFx9sgtfbAHG2sZ0KMPcgyzJEDcabIeDjZW2+Lm+x2mfJbszctObYPlxSvvN4h2ziWQBq0hQnAVRBoAeDExO/6r6+2PUl/Exgi6wZiq4tCGX7q8W9IGVYlvxMEeFNsP4+4NXaDvEJNCbDilOsICPdF5u0vp+I796A2205s7BcCcGxUsyOW92LlW9dfuD2YEY1RLDnIiYP6tEK4EAzwSKG03HhzfdLASN1cQmIZLiKc1A3B1sj/NL2A2svuToHWFUJIeTlz0X2hHGLNWhxnPE4wZG0kB/p5kPGZXuPb93+/xGnBMMZzjV1JIydRb4pMNoD51EllxTekWWDYFCqNzqNgS1L41dn+bknr883x9ySeEswM9XkW6q7KEqxPdCm256ScpnYTnnb+fOzuXLb1zV6gz8qburak2jjRCbtOBaJCLJCMi4NqdUyCUmDz8=
  on:
    tag: true
    branch: main
