language: python
python:
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  username: ArneTillmann
  password:
    secure: eyYZlfGrvhkKKCVhCcWDihbHKldl3lNsbXsPbQIPBdN2aRoeQN5baIgKImxZKusNpkYjdLYwBfLM394jjOkur814b/ga7lf8eIq4o8R5GM9+Msdsbx5irdCwNXqoPijuaIRP90LIiBVHS1g2FOVNef3Cvd/eW9W2NgMcMsSptalCfU98/B4fFVfF7efgK4MOxoGd/97g+0I9/eake6Z/10D6Ukg9hcOE2MfSt9f+j5ydhNptSviiyneioAcBuPOgFRHvR+Cjgk9nyUTvf7I3Nh3CnuLnRzBemT0euzZTUpwh0G+wJQ3gLW2ePDiCz/8H4YHTOT8t29vGcRRHhwKgG3AyxWttaEOzEHVZTQPnSbvWtSkNTZV0HDiF29+5oCGAfv5dsUUg9dLGooRHhNYPbvwzmzvvZIgjjy/5DzzqSF9b9oScXHxILqTxUj43yvgJIUoycckyR8S+1lfDfwwbO9atDbn9bVRXnNJwXFrPPiEpohM/8KlsW2exnoo0xF3dCgY1NuUFr0A9W7y1AWQzcfgb9VUTVhwu8smvWUMCtKQ5DCZO0u1t7U0qUGrgPC+CIAhRuOXwocTRdGTurn1/FRbrYdHA1hjk3AmFyhvNLFpwJKktH084VvQtdguX6TD67BnYxkkBkllVEc5TkzK1NNYwjJJ1OFOMZWMvyhyog88=
  on:
    tag: true
    branch: main
